/**
 * Seed data — 50 typical construction catalog items.
 *
 * Covers common electrical, plumbing, hardware, and consumables that the
 * MVP norms reference. Real contractor catalogs have thousands; this seed
 * is enough to exercise all document + AI flows end-to-end in Phase 0-1.
 */

import type { PurchaseUOM } from '../../core/types';

export interface ItemSeed {
  id: string;
  sku: string;
  name: string;
  category: string;
  baseUOM: string;
  purchaseUOMs: PurchaseUOM[];
  allowedIssueUOMs: string[];
  lastPurchasePrice: number;
  averageCost: number;
  minStock?: number;
  isTrackable?: boolean;
  notes?: string;
}

const defaultPair = (uom: string, factor: number): PurchaseUOM[] => [
  { uom, factor, isDefault: true },
];

export const SEED_ITEMS: readonly ItemSeed[] = [
  // ── Electrical: Wire ────────────────────────────────────────────────
  {
    id: 'item_wire_12_2_nmb',
    sku: 'WIRE-12-2-NMB',
    name: 'Wire 12-2 NM-B THHN (copper)',
    category: 'cat_electrical_cable',
    baseUOM: 'ft',
    purchaseUOMs: [
      { uom: 'ft', factor: 1, isDefault: false },
      { uom: 'roll_250ft', factor: 250, isDefault: true },
      { uom: 'roll_500ft', factor: 500, isDefault: false },
    ],
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.36,
    averageCost: 0.36,
    minStock: 100,
  },
  {
    id: 'item_wire_14_2_nmb',
    sku: 'WIRE-14-2-NMB',
    name: 'Wire 14-2 NM-B',
    category: 'cat_electrical_cable',
    baseUOM: 'ft',
    purchaseUOMs: [
      { uom: 'ft', factor: 1, isDefault: false },
      { uom: 'roll_250ft', factor: 250, isDefault: true },
    ],
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.28,
    averageCost: 0.28,
    minStock: 100,
  },
  {
    id: 'item_wire_12_3_nmb',
    sku: 'WIRE-12-3-NMB',
    name: 'Wire 12-3 NM-B (3-conductor)',
    category: 'cat_electrical_cable',
    baseUOM: 'ft',
    purchaseUOMs: defaultPair('roll_250ft', 250),
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.48,
    averageCost: 0.48,
    minStock: 50,
  },
  {
    id: 'item_wire_thhn_12',
    sku: 'WIRE-THHN-12',
    name: 'THHN 12 AWG (single conductor)',
    category: 'cat_electrical_cable',
    baseUOM: 'ft',
    purchaseUOMs: [
      { uom: 'ft', factor: 1, isDefault: false },
      { uom: 'roll_500ft', factor: 500, isDefault: true },
    ],
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.22,
    averageCost: 0.22,
    minStock: 200,
  },

  // ── Electrical: Devices ─────────────────────────────────────────────
  {
    id: 'item_outlet_15a_white',
    sku: 'OUTLET-15A-WHT',
    name: 'Outlet 15A Duplex White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 2.49,
    averageCost: 2.49,
    minStock: 40,
  },
  {
    id: 'item_outlet_20a_white',
    sku: 'OUTLET-20A-WHT',
    name: 'Outlet 20A Dedicated White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 4.5,
    averageCost: 4.5,
    minStock: 10,
  },
  {
    id: 'item_gfci_15a',
    sku: 'GFCI-15A',
    name: 'GFCI Outlet 15A',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 14.5,
    averageCost: 14.5,
    minStock: 10,
  },
  {
    id: 'item_switch_spst_white',
    sku: 'SWITCH-SPST-WHT',
    name: 'Switch SPST White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 1.9,
    averageCost: 1.9,
    minStock: 30,
  },
  {
    id: 'item_switch_3way_white',
    sku: 'SWITCH-3WAY-WHT',
    name: 'Switch 3-Way White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 4.25,
    averageCost: 4.25,
    minStock: 10,
  },
  {
    id: 'item_dimmer_single_pole',
    sku: 'DIMMER-SP',
    name: 'Dimmer Single-Pole',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 18.0,
    averageCost: 18.0,
    minStock: 5,
  },
  {
    id: 'item_wall_plate_1g_white',
    sku: 'WPLATE-1G-WHT',
    name: 'Wall Plate 1-Gang White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.65,
    averageCost: 0.65,
    minStock: 40,
  },
  {
    id: 'item_wall_plate_2g_white',
    sku: 'WPLATE-2G-WHT',
    name: 'Wall Plate 2-Gang White',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 1.2,
    averageCost: 1.2,
    minStock: 20,
  },
  {
    id: 'item_box_1g_plastic',
    sku: 'BOX-1G-PL',
    name: 'Electrical Box 1-Gang (plastic)',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.95,
    averageCost: 0.95,
    minStock: 30,
  },
  {
    id: 'item_box_2g_plastic',
    sku: 'BOX-2G-PL',
    name: 'Electrical Box 2-Gang',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 1.55,
    averageCost: 1.55,
    minStock: 15,
  },
  {
    id: 'item_junction_box_4sq',
    sku: 'JBOX-4SQ',
    name: 'Junction Box 4-inch Square',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 4.5,
    averageCost: 4.5,
    minStock: 10,
  },
  {
    id: 'item_fan_support_box',
    sku: 'FANBOX-CEIL',
    name: 'Fan Support Box (ceiling)',
    category: 'cat_electrical_device',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 6.5,
    averageCost: 6.5,
    minStock: 5,
  },

  // ── Electrical: Fixtures ────────────────────────────────────────────
  {
    id: 'item_ceiling_fan_52',
    sku: 'FAN-CEIL-52',
    name: 'Ceiling Fan 52" with Light',
    category: 'cat_electrical_fixture',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 89.0,
    averageCost: 89.0,
    minStock: 0,
  },
  {
    id: 'item_recessed_led_6',
    sku: 'LED-RCD-6',
    name: 'Recessed LED 6-inch',
    category: 'cat_electrical_fixture',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 32.0,
    averageCost: 32.0,
    minStock: 4,
  },
  {
    id: 'item_led_bulb_a19',
    sku: 'BULB-A19-LED',
    name: 'LED Bulb A19 60W-equiv',
    category: 'cat_electrical_fixture',
    baseUOM: 'each',
    purchaseUOMs: [
      { uom: 'each', factor: 1, isDefault: false },
      { uom: 'pack_4', factor: 4, isDefault: true },
    ],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 2.5,
    averageCost: 2.5,
    minStock: 20,
  },
  {
    id: 'item_light_fixture_basic',
    sku: 'FIX-BASIC',
    name: 'Basic Ceiling Light Fixture',
    category: 'cat_electrical_fixture',
    baseUOM: 'each',
    purchaseUOMs: defaultPair('each', 1),
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 24.0,
    averageCost: 24.0,
    minStock: 2,
  },

  // ── Electrical: Misc consumables ────────────────────────────────────
  {
    id: 'item_wirenut_yellow',
    sku: 'WIRENUT-YEL',
    name: 'Wire Nut Yellow (12-10 AWG)',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [
      { uom: 'each', factor: 1, isDefault: false },
      { uom: 'pack_100', factor: 100, isDefault: true },
    ],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.12,
    averageCost: 0.12,
    minStock: 200,
  },
  {
    id: 'item_wirenut_red',
    sku: 'WIRENUT-RED',
    name: 'Wire Nut Red (18-10 AWG)',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'pack_100', factor: 100, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.15,
    averageCost: 0.15,
    minStock: 100,
  },
  {
    id: 'item_electrical_tape',
    sku: 'TAPE-ELEC',
    name: 'Electrical Tape Black 3/4"',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 1.8,
    averageCost: 1.8,
    minStock: 15,
  },
  {
    id: 'item_cable_staples',
    sku: 'STAPLES-CABLE',
    name: 'Cable Staples 3/8" (Romex)',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'pack_100', factor: 100, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.05,
    averageCost: 0.05,
    minStock: 200,
  },

  // ── Plumbing ────────────────────────────────────────────────────────
  {
    id: 'item_teflon_tape',
    sku: 'TEFLON-TAPE',
    name: 'Teflon Tape 1/2"',
    category: 'cat_plumbing_fittings',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 1.5,
    averageCost: 1.5,
    minStock: 10,
  },
  {
    id: 'item_pipe_pvc_05',
    sku: 'PVC-1-2',
    name: 'PVC Pipe 1/2" × 10ft',
    category: 'cat_plumbing_fittings',
    baseUOM: 'ft',
    purchaseUOMs: [
      { uom: 'ft', factor: 1, isDefault: false },
      { uom: 'stick_10ft', factor: 10, isDefault: true },
    ],
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.3,
    averageCost: 0.3,
    minStock: 50,
  },
  {
    id: 'item_pipe_pvc_1',
    sku: 'PVC-1',
    name: 'PVC Pipe 1"',
    category: 'cat_plumbing_fittings',
    baseUOM: 'ft',
    purchaseUOMs: [{ uom: 'stick_10ft', factor: 10, isDefault: true }],
    allowedIssueUOMs: ['ft'],
    lastPurchasePrice: 0.55,
    averageCost: 0.55,
    minStock: 30,
  },
  {
    id: 'item_pvc_elbow_05',
    sku: 'PVC-ELB-1-2',
    name: 'PVC Elbow 1/2"',
    category: 'cat_plumbing_fittings',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.45,
    averageCost: 0.45,
    minStock: 20,
  },
  {
    id: 'item_pvc_coupling_05',
    sku: 'PVC-CPL-1-2',
    name: 'PVC Coupling 1/2"',
    category: 'cat_plumbing_fittings',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.35,
    averageCost: 0.35,
    minStock: 20,
  },
  {
    id: 'item_pvc_cement',
    sku: 'PVC-CEM',
    name: 'PVC Cement 4oz',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 5.5,
    averageCost: 5.5,
    minStock: 4,
  },
  {
    id: 'item_faucet_basic',
    sku: 'FAUCET-BASIC',
    name: 'Basic Kitchen Faucet',
    category: 'cat_plumbing',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 65.0,
    averageCost: 65.0,
    minStock: 0,
  },
  {
    id: 'item_supply_line_12',
    sku: 'SUPPLY-12',
    name: 'Supply Line 12" Braided',
    category: 'cat_plumbing_fittings',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 4.5,
    averageCost: 4.5,
    minStock: 10,
  },

  // ── Hardware ────────────────────────────────────────────────────────
  {
    id: 'item_drywall_screw_158',
    sku: 'SCREW-DW-158',
    name: 'Drywall Screw 1-5/8"',
    category: 'cat_hardware',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'box_500', factor: 500, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.03,
    averageCost: 0.03,
    minStock: 1000,
  },
  {
    id: 'item_wood_screw_2',
    sku: 'SCREW-WD-2',
    name: 'Wood Screw #8 × 2"',
    category: 'cat_hardware',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'box_100', factor: 100, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.06,
    averageCost: 0.06,
    minStock: 300,
  },
  {
    id: 'item_anchor_toggle',
    sku: 'ANCHOR-TGL',
    name: 'Toggle Bolt Anchor 1/4"',
    category: 'cat_hardware',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'pack_25', factor: 25, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 0.35,
    averageCost: 0.35,
    minStock: 50,
  },

  // ── Drywall / paint consumables ─────────────────────────────────────
  {
    id: 'item_drywall_tape',
    sku: 'DW-TAPE',
    name: 'Drywall Joint Tape',
    category: 'cat_consumables',
    baseUOM: 'roll',
    purchaseUOMs: [{ uom: 'roll', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['roll'],
    lastPurchasePrice: 6.5,
    averageCost: 6.5,
    minStock: 3,
  },
  {
    id: 'item_joint_compound',
    sku: 'JC-5GAL',
    name: 'Joint Compound 5-gallon',
    category: 'cat_consumables',
    baseUOM: 'bucket',
    purchaseUOMs: [{ uom: 'bucket', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['bucket'],
    lastPurchasePrice: 18.0,
    averageCost: 18.0,
    minStock: 2,
  },
  {
    id: 'item_primer_1gal',
    sku: 'PRIMER-1G',
    name: 'Primer Paint 1-gallon',
    category: 'cat_consumables',
    baseUOM: 'gal',
    purchaseUOMs: [{ uom: 'gal', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['gal'],
    lastPurchasePrice: 22.0,
    averageCost: 22.0,
    minStock: 2,
  },
  {
    id: 'item_paint_white_1gal',
    sku: 'PAINT-WH-1G',
    name: 'Interior Paint White 1-gallon',
    category: 'cat_consumables',
    baseUOM: 'gal',
    purchaseUOMs: [{ uom: 'gal', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['gal'],
    lastPurchasePrice: 35.0,
    averageCost: 35.0,
    minStock: 3,
  },
  {
    id: 'item_caulk_white',
    sku: 'CAULK-WH',
    name: 'Caulk White 10.1 oz',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 4.5,
    averageCost: 4.5,
    minStock: 10,
  },

  // ── HVAC ────────────────────────────────────────────────────────────
  {
    id: 'item_hvac_filter_20x25',
    sku: 'FILTER-20X25',
    name: 'HVAC Filter 20x25x1',
    category: 'cat_hvac',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 8.0,
    averageCost: 8.0,
    minStock: 6,
  },
  {
    id: 'item_duct_tape',
    sku: 'TAPE-DUCT',
    name: 'Duct Tape (metallic foil)',
    category: 'cat_consumables',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 8.5,
    averageCost: 8.5,
    minStock: 4,
  },

  // ── Tools (trackable) ───────────────────────────────────────────────
  {
    id: 'item_tool_voltage_tester',
    sku: 'TOOL-VTESTER',
    name: 'Voltage Tester (non-contact)',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 22.0,
    averageCost: 22.0,
    isTrackable: true,
    minStock: 2,
  },
  {
    id: 'item_tool_pliers_linemans',
    sku: 'TOOL-PLIERS-LM',
    name: "Lineman's Pliers 9\"",
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 38.0,
    averageCost: 38.0,
    isTrackable: true,
    minStock: 1,
  },
  {
    id: 'item_tool_wire_stripper',
    sku: 'TOOL-WSTRIP',
    name: 'Wire Stripper (10-18 AWG)',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 24.0,
    averageCost: 24.0,
    isTrackable: true,
    minStock: 1,
  },
  {
    id: 'item_tool_drill_battery',
    sku: 'TOOL-DRILL',
    name: 'Cordless Drill 18V',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 149.0,
    averageCost: 149.0,
    isTrackable: true,
  },
  {
    id: 'item_drill_bit_set',
    sku: 'DRILL-BIT-SET',
    name: 'Drill Bit Set (titanium, 20pc)',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 42.0,
    averageCost: 42.0,
    minStock: 1,
  },
  {
    id: 'item_tool_tape_measure_25',
    sku: 'TOOL-TAPE-25',
    name: 'Tape Measure 25ft',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 18.0,
    averageCost: 18.0,
    isTrackable: true,
  },
  {
    id: 'item_tool_stud_finder',
    sku: 'TOOL-STUD',
    name: 'Stud Finder Electronic',
    category: 'cat_tools',
    baseUOM: 'each',
    purchaseUOMs: [{ uom: 'each', factor: 1, isDefault: true }],
    allowedIssueUOMs: ['each'],
    lastPurchasePrice: 35.0,
    averageCost: 35.0,
    isTrackable: true,
  },
];

// Sanity check at module load time — fail fast in tests if a seed is malformed.
if (new Set(SEED_ITEMS.map((i) => i.sku)).size !== SEED_ITEMS.length) {
  throw new Error('SEED_ITEMS contains duplicate SKUs');
}
if (new Set(SEED_ITEMS.map((i) => i.id)).size !== SEED_ITEMS.length) {
  throw new Error('SEED_ITEMS contains duplicate ids');
}
