/**
 * FirestoreFile — `files/{id}` adapter.
 *
 * Implements {@link FilePort} on top of Firebase Admin Firestore. Tracks
 * Firestore-side metadata for uploads (acceptance act PDFs, photo
 * evidence, wiki attachments). Distinct from `StorageUploadPort`, which
 * handles the raw blob in Firebase Storage.
 *
 * See spec/04-storage/adapter-mapping.md §24 FilePort.
 *
 * Indexes:
 *   - `(linkedTo.taskId, uploadedAt desc)`  EXISTING — firestore.indexes.json:854-866
 *
 * Conventions:
 *   - Timestamps converted at the boundary via `toEpochMs`.
 *   - `registerUpload` writes `linkedTo: { taskId, clientId?, projectId? }`
 *     so the existing composite index is hit on later `findByTask`.
 *   - `null` for not-found.
 */

import { Timestamp } from 'firebase-admin/firestore';
import type { Firestore } from 'firebase-admin/firestore';

import type { FilePort, FileMetadata } from '../../ports/infra/FilePort';
import {
  asClientId,
  asFileId,
  asProjectId,
  asTaskId,
  type FileId,
  type TaskId,
} from '../../domain/identifiers';
import { mapFirestoreError } from '../errors';
import {
  type AdapterLogger,
  noopLogger,
  stripUndefined,
  toEpochMs,
} from './_shared';

const COLLECTION = 'files';

export class FirestoreFile implements FilePort {
  constructor(
    private readonly db: Firestore,
    private readonly logger: AdapterLogger = noopLogger,
  ) {}

  /**
   * List file metadata records linked to a task, newest first.
   *
   * Adapter mapping (§24 row 1):
   *   `where linkedTo.taskId == X .orderBy uploadedAt desc`.
   * Existing index: `(linkedTo.taskId, uploadedAt desc)`.
   */
  async findByTask(taskId: TaskId): Promise<FileMetadata[]> {
    try {
      const q = this.db
        .collection(COLLECTION)
        .where('linkedTo.taskId', '==', taskId)
        .orderBy('uploadedAt', 'desc');
      const snap = await q.get();
      return snap.docs
        .map((d) => {
          const data = d.data();
          return data ? mapToMetadata(data, d.id) : null;
        })
        .filter((x): x is FileMetadata => x !== null);
    } catch (err) {
      this.logger.error?.('FirestoreFile.findByTask failed', { taskId, err });
      throw mapFirestoreError(err, { op: 'File.findByTask', taskId });
    }
  }

  /**
   * Read a single file metadata record by id.
   *
   * Adapter mapping (§24 row 2):
   *   `get files/{id}`. Returns `null` if not found.
   */
  async findById(id: FileId): Promise<FileMetadata | null> {
    try {
      const snap = await this.db.collection(COLLECTION).doc(id).get();
      if (!snap.exists) return null;
      const data = snap.data();
      if (!data) return null;
      return mapToMetadata(data, snap.id);
    } catch (err) {
      this.logger.error?.('FirestoreFile.findById failed', { id, err });
      throw mapFirestoreError(err, { op: 'File.findById', id });
    }
  }

  /**
   * Insert a new metadata record after `StorageUploadPort.upload`. Doc id
   * auto-generated by Firestore. `uploadedAt` is converted from EpochMs.
   *
   * Adapter mapping (§24 row 3):
   *   `add files/{auto-id}` with `linkedTo: { taskId?, clientId?, projectId? }`.
   */
  async registerUpload(meta: Omit<FileMetadata, 'id'>): Promise<{ id: FileId }> {
    try {
      const ref = this.db.collection(COLLECTION).doc();
      const linkedTo = meta.linkedTo
        ? stripUndefined({
            taskId: meta.linkedTo.taskId,
            clientId: meta.linkedTo.clientId,
            projectId: meta.linkedTo.projectId,
          })
        : undefined;

      const payload: Record<string, unknown> = stripUndefined({
        url: meta.url,
        name: meta.name,
        mime: meta.mime,
        category: meta.category,
        linkedTo,
        uploadedAt: Timestamp.fromMillis(meta.uploadedAt),
        uploadedBy: meta.uploadedBy,
      });
      await ref.set(payload);
      return { id: asFileId(ref.id) };
    } catch (err) {
      this.logger.error?.('FirestoreFile.registerUpload failed', {
        name: meta.name,
        err,
      });
      throw mapFirestoreError(err, {
        op: 'File.registerUpload',
        name: meta.name,
      });
    }
  }
}

// ─── Internal: Firestore data → FileMetadata ───────────────────────────

function mapToMetadata(
  data: FirebaseFirestore.DocumentData,
  id: string,
): FileMetadata {
  const result: FileMetadata = {
    id: asFileId(id),
    url: String(data.url ?? ''),
    name: String(data.name ?? ''),
    mime: String(data.mime ?? ''),
    uploadedAt: toEpochMs(data.uploadedAt) ?? 0,
  };
  if (typeof data.category === 'string') result.category = data.category;
  if (typeof data.uploadedBy === 'string') result.uploadedBy = data.uploadedBy;

  const lt = data.linkedTo as
    | { taskId?: unknown; clientId?: unknown; projectId?: unknown }
    | undefined;
  if (lt && typeof lt === 'object') {
    const linked: FileMetadata['linkedTo'] = {};
    if (typeof lt.taskId === 'string' && lt.taskId.length > 0) {
      linked.taskId = asTaskId(lt.taskId);
    }
    if (typeof lt.clientId === 'string' && lt.clientId.length > 0) {
      linked.clientId = asClientId(lt.clientId);
    }
    if (typeof lt.projectId === 'string' && lt.projectId.length > 0) {
      linked.projectId = asProjectId(lt.projectId);
    }
    if (Object.keys(linked).length > 0) result.linkedTo = linked;
  }
  return result;
}
