/**
 * FirestoreAIAudit — `aiAuditLogs/{auto-id}` adapter.
 *
 * Implements {@link AIAuditPort} on top of Firebase Admin Firestore.
 * Append-only log of every AI-driven flow (generate_task / estimate_minutes
 * / modify_task / decompose_estimate) for accuracy analysis and cost
 * tracking.
 *
 * See spec/04-storage/adapter-mapping.md §15 AIAuditPort.
 *
 * Conventions:
 *   - Append-only — no read methods on the port.
 *   - `createdAt` is converted from `EpochMs` → `Timestamp` on write.
 *   - Doc id is auto-generated by Firestore.
 */

import { Timestamp } from 'firebase-admin/firestore';
import type { Firestore } from 'firebase-admin/firestore';

import type { AIAuditPort, AIAuditEntry } from '../../ports/ai/AIAuditPort';
import { mapFirestoreError } from '../errors';
import { type AdapterLogger, noopLogger, stripUndefined } from './_shared';

const COLLECTION = 'aiAuditLogs';

export class FirestoreAIAudit implements AIAuditPort {
  constructor(
    private readonly db: Firestore,
    private readonly logger: AdapterLogger = noopLogger,
  ) {}

  /**
   * Append a new AI audit entry. Returns the auto-generated doc id.
   *
   * Adapter mapping (§15 row 1):
   *   `add` to `aiAuditLogs/{auto-id}`. `createdAt` written as
   *   `Timestamp.fromMillis(entry.createdAt)`.
   */
  async append(entry: AIAuditEntry): Promise<{ id: string }> {
    try {
      const ref = this.db.collection(COLLECTION).doc();
      const payload: Record<string, unknown> = stripUndefined({
        companyId: entry.companyId,
        userId: entry.userId,
        taskId: entry.taskId,
        flow: entry.flow,
        prompt: entry.prompt,
        response: entry.response,
        confidence: entry.confidence,
        model: entry.model,
        tokensIn: entry.tokensIn,
        tokensOut: entry.tokensOut,
        costUsd: entry.costUsd,
        userEdits: entry.userEdits,
        createdAt: Timestamp.fromMillis(entry.createdAt),
      });
      await ref.set(payload);
      return { id: ref.id };
    } catch (err) {
      this.logger.error?.('FirestoreAIAudit.append failed', {
        flow: entry.flow,
        companyId: entry.companyId,
        err,
      });
      throw mapFirestoreError(err, {
        op: 'AIAudit.append',
        flow: entry.flow,
      });
    }
  }
}
